### ISSUE TITLE
Linux support and weird data location

### ISSUE THREAD

**Issue by alexcoder04** [BoettcherDasOriginal/LeoConsole#1]
As .NET is available for Linux, it should be not a big problem to support it. I could build and use LeoConsole successfully on Debian, however some paths are hardcoded to use backslashes:

![scrot-220105_151110](https://user-images.githubusercontent.com/70093931/148231565-ecc460aa-699f-49d9-8c17-601cee59a557.png)

So a folder with backslashes in its name is created, rather that a subfolder. C# should have some kind os `path.join(foldername, subfolderName)` function, which builds a path using system default's path separator.

---

The other thing is that the program uses relative paths for storing settings, so it depends on the folder you run the program from. For example:

```text
src
 |- LeoConsole
 |   |- Properties
 |   |- bin
 |   |   |- Debug
 |   |- data
 |   |- obj
```

If I run it from the `LeoConsole` folder, it creates the shown `data` folder. However, if I `cd` into the `bin` folder, it expects `data` to be inside `bin` and tells that it couldn't find it.

---

Furthermore, it would be nice to have an option to disable automatic updates, because they don't make sense on Linux (we don't need to download a windows binary).

**Comment by BoettcherDasOriginal** [comment]
Thank you for your feedback!
I will try to improve these things in the next versions

**Comment by BoettcherDasOriginal** [comment]
Check out [LeoConsole v1.4.1 Changelogs ](https://github.com/BoettcherDasOriginal/LeoConsole/releases/tag/1.4.1)
