### ISSUE TITLE
[Bug] Cannot use console data in PluginMain

### ISSUE THREAD

**Issue by alexcoder04** [BoettcherDasOriginal/LeoConsole#12]
Maybe I am doing something wrong, but it seems to me that the data values are not set yet, when `PluginMain()` runs. Is there a way to fix it?

my code:
```C#
public void PluginMain()
{
  _data = new ConsoleData();
  Console.WriteLine(_data.SavePath); // is null
  // ...
}
```

**Comment by alexcoder04** [comment]
Here is my code:
```c#
 public void PluginMain(){
  _data = new ConsoleData();
      
  _Commands = new List<ICommand>();
  _Commands.Add(new Script());
  _Commands.Add(new ListScripts());
  _Commands.Add(new Exec());

  Console.WriteLine("savepath: " + _data.SavePath + ".");
  Console.WriteLine("savepath: " + data.SavePath + ".");
}
```

And here is the output:

```dosini
Startet...
Keine Updates Gefunden!
Lädt: Users.lcs
Users.lcs erfolgreich geladen
Lädt: Plugins
savepath: . # <- nothing here
savepath: . # <- nothing here
Erfolgreich 5 Plugins geladen!
Registriere: Datas
Erfolgreich 6 Datas registriert!
Registriere: Commands
Erfolgreich 30 Commands registriert!

--- LeoConsole v1.5.0 ---
```

**Comment by BoettcherDasOriginal** [comment]
> Here is my code:
> 
> ```cs
>  public void PluginMain(){
>   _data = new ConsoleData();
>       
>   _Commands = new List<ICommand>();
>   _Commands.Add(new Script());
>   _Commands.Add(new ListScripts());
>   _Commands.Add(new Exec());
> 
>   Console.WriteLine("savepath: " + _data.SavePath + ".");
>   Console.WriteLine("savepath: " + data.SavePath + ".");
> }
> ```
> 
> And here is the output:
> 
> ```ini
> Startet...
> Keine Updates Gefunden!
> Lädt: Users.lcs
> Users.lcs erfolgreich geladen
> Lädt: Plugins
> savepath: . # <- nothing here
> savepath: . # <- nothing here
> Erfolgreich 5 Plugins geladen!
> Registriere: Datas
> Erfolgreich 6 Datas registriert!
> Registriere: Commands
> Erfolgreich 30 Commands registriert!
> 
> --- LeoConsole v1.5.0 ---
> ```

I found the mistake.
You can not use ``_data.SavePath`` in ``PluginMain()``, because ``data`` will be registered after ``PluginMain()`` is called.
I will fix this in the next version.

**Comment by BoettcherDasOriginal** [comment]
I tried to *fix* it, but due to the register mechanic, it is impossible to fix it.
Why do you want to use it in ``PluginMain()``?

**Comment by alexcoder04** [comment]
> I tried to _fix_ it, but due to the register mechanic, it is impossible to fix it. Why do you want to use it in `PluginMain()`? @alexcoder04

I want to check the SavePath location and create the scripts folder inside.

What about renaming `PluginMain()` to something like `PluginInit()` and adding another `PluginMain()` function, which is called after `data` is registered?

**Comment by BoettcherDasOriginal** [comment]
> > I tried to _fix_ it, but due to the register mechanic, it is impossible to fix it. Why do you want to use it in `PluginMain()`? @alexcoder04
> 
> I want to check the SavePath location and create the scripts folder inside.
> 
> What about renaming `PluginMain()` to something like `PluginInit()` and adding another `PluginMain()` function, which is called after `data` is registered?

yeah, this might could be a solution, I think I will do it like this
