### ISSUE TITLE
[Rework] Package System rework

### ISSUE THREAD

**Issue by BoettcherDasOriginal** [BoettcherDasOriginal/LeoConsole#17]
# To do:

- [x] rework old package manager ``pkg``
- [x] add ``default plugins``, which will be install automatically when first starting LeoConsole
- [x] add [``apkg``](https://github.com/alexcoder04/LeoConsole-apkg) from @alexcoder04 as an default plugin

**Comment by alexcoder04** [comment]
Hello, I wanted to ask some further questions about the package system in the future.

1. Are you planning to fork apkg or contribute to the main version?
2. Default plugins will be just normal plugins, won't they? So no special abilities like pre-installed Android apps?
3. I was planning to add a couple of features to apkg (https://github.com/alexcoder04/LeoConsole-apkg/issues/1), however I would need some plugin functions to be available, so what do you think about starting a discussion to coordinate the work?

**Comment by BoettcherDasOriginal** [comment]
Hi, im planning to contribute to the main version of apkg and add it as an default plugin.
Default plugins will be just like normal plugins, except they will be automatically installed. (The user has the option to delete the default plugins later)
I think it's a good idea to start a discussion to coordinate work and support each other.

**Comment by BoettcherDasOriginal** [comment]
> Hello, I wanted to ask some further questions about the package system in the future.
> 
> 1. Are you planning to fork apkg or contribute to the main version?
> 2. Default plugins will be just normal plugins, won't they? So no special abilities like pre-installed Android apps?
> 3. I was planning to add a couple of features to apkg ([Current TODOs alexcoder04/LeoConsole-apkg#1](https://github.com/alexcoder04/LeoConsole-apkg/issues/1)), however I would need some plugin functions to be available, so what do you think about starting a discussion to coordinate the work?

Hi, im planning to contribute to the main version of apkg and add it as an default plugin.
Default plugins will be just like normal plugins, except they will be automatically installed. (The user has the option to delete the default plugins later)
I think it's a good idea to start a discussion to coordinate work and support each other.
