### ISSUE TITLE
Build and install custom plugins

### ISSUE THREAD

**Issue by alexcoder04** [BoettcherDasOriginal/LeoConsole#2]
I have some interesting ideas for plugins I want to write. Is it currently possible to build and install custom plugins? If not, is this planned to be implemented in future?

**Comment by BoettcherDasOriginal** [comment]
Yes, it is possible.
Maybe this will help you: [LeoConsole Plugin Tutorial](https://github.com/BoettcherDasOriginal/LeoConsole/wiki/Plugin-Tutorial)

**Comment by alexcoder04** [comment]
Did not see it, thank you very much
