### ISSUE TITLE
[Bug] CurrentWorkingPath and User.name not defined in PluginMain yet

### ISSUE THREAD

**Issue by alexcoder04** [BoettcherDasOriginal/LeoConsole#38]
## Description
Not sure if it is a bug or a feature, but `data.CurrentWorkingPath` is not defined yet when `PluginMain()` is called.

**Edit**: `data.User.name` is null as well, however `data.SavePath` is set.

## Steps to Reproduce
1. Create a plugin that uses `data.CurrentWorkingPath` in its `PluginMain` method
2. Run it

## Version with bug
Latest git

**Comment by BoettcherDasOriginal** [comment]
This is not a bug, it works as intended. The user is NULL because the user has not yet logged in. Almost the same applies to the working directory: It is NULL because the default working directory will be slightly different for each user in the future. For example: ``data/Users/<USERNAME>/``
